#!/usr/bin/perl

use warnings;
use strict;
use Fcntl;
use POSIX;

mkfifo("bla", 0666) or die "Fehler bei mknod bla: $!\n";
warn "$0: bla als benannte Pipe erzeugt.\n";

open(FIFO, ">", "bla") or die "bla\n";
print FIFO "huhu";
close FIFO;
print "huhu";

open(FIFO, "<", "bla") or die "blu\n";
my $bla = <FIFO>;
print "$bla\n";
