#!/usr/bin/perl

use warnings;

for (@ARGV) {
    if (int(rand 2)) {
        $player1 = sub {int(rand 10)};
        $player2 = sub {11}
    } else {
        $player1 = sub {11};
        $player2 = sub {int(rand 10)};
    }

    open FILE, ">>", $_;
    print FILE &$player1, " ", &$player2, "\n",
               &$player1, " ", &$player2;
}
