#!/usr/bin/perl

use warnings;
use strict;
use Net::CUPS;
use Net::CUPS::Destination;
$|++;

my $cups = Net::CUPS->new();
my @printers = $cups->getDestinations();
print "@printers\n";

print($_->getName(), "\n") for (@printers);
my $printer = $cups->getDestination("HP_Laserjet_6P");
$printer->addOption("cpi", 12);
#print $printer->getOptions() . "\n";
open PRINTFILE, ">", "printfile";
print PRINTFILE "1234567890" x 8 . "123456789";
close PRINTFILE;
#open PRINTFILE, "<", "printfile";

my $jobid = $printer->printFile("printfile", "huhu");
print $jobid;
